May 01 17:07:10 cloud-init[2416]: handlers.py[DEBUG]: finish: modules-final/config-scripts-per-instance: SUCCESS: config-scripts-per-instance previously ran
May 01 17:07:10 cloud-init[2416]: stages.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) with frequency once-per-instance
May 01 17:07:10 cloud-init[2416]: handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency once-per-instance
May 01 17:07:10 cloud-init[2416]: helpers.py[DEBUG]: config-scripts-user already ran (freq=once-per-instance)
May 01 17:07:10 cloud-init[2416]: handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user previously ran
May 01 17:07:10 cloud-init[2416]: stages.py[DEBUG]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_ssh_authkey_fingerprints.pyc'>) with frequency once-per-instance
May 01 17:07:10 cloud-init[2416]: handlers.py[DEBUG]: start: modules-final/config-ssh-authkey-fingerprints: running config-ssh-authkey-fingerprints with frequency once-per-instance
May 01 17:07:10 cloud-init[2416]: helpers.py[DEBUG]: config-ssh-authkey-fingerprints already ran (freq=once-per-instance)
May 01 17:07:10 cloud-init[2416]: handlers.py[DEBUG]: finish: modules-final/config-ssh-authkey-fingerprints: SUCCESS: config-ssh-authkey-fingerprints previously ran
May 01 17:07:10 cloud-init[2416]: stages.py[DEBUG]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_keys_to_console.pyc'>) with frequency once-per-instance
May 01 17:07:10 cloud-init[2416]: handlers.py[DEBUG]: start: modules-final/config-keys-to-console: running config-keys-to-console with frequency once-per-instance
May 01 17:07:10 cloud-init[2416]: helpers.py[DEBUG]: config-keys-to-console already ran (freq=once-per-instance)
May 01 17:07:10 cloud-init[2416]: handlers.py[DEBUG]: finish: modules-final/config-keys-to-console: SUCCESS: config-keys-to-console previously ran
May 01 17:07:10 cloud-init[2416]: stages.py[DEBUG]: Running module phone-home (<module 'cloudinit.config.cc_phone_home' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_phone_home.pyc'>) with frequency once-per-instance
May 01 17:07:10 cloud-init[2416]: handlers.py[DEBUG]: start: modules-final/config-phone-home: running config-phone-home with frequency once-per-instance
May 01 17:07:10 cloud-init[2416]: helpers.py[DEBUG]: config-phone-home already ran (freq=once-per-instance)
May 01 17:07:10 cloud-init[2416]: handlers.py[DEBUG]: finish: modules-final/config-phone-home: SUCCESS: config-phone-home previously ran
May 01 17:07:10 cloud-init[2416]: stages.py[DEBUG]: Running module final-message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_final_message.pyc'>) with frequency always
May 01 17:07:10 cloud-init[2416]: handlers.py[DEBUG]: start: modules-final/config-final-message: running config-final-message with frequency always
May 01 17:07:10 cloud-init[2416]: helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x7fb5f2438a50>)
May 01 17:07:10 cloud-init[2416]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
May 01 17:07:10 cloud-init[2416]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
May 01 17:07:10 cloud-init[2416]: util.py[DEBUG]: Cloud-init v. 19.3-43.amzn2 finished at Sat, 01 May 2021 17:07:10 +0000. Datasource DataSourceNone.  Up 20.63 seconds
May 01 17:07:10 cloud-init[2416]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 59 bytes
May 01 17:07:10 cloud-init[2416]: cc_final_message.py[WARNING]: Used fallback datasource
May 01 17:07:10 cloud-init[2416]: handlers.py[DEBUG]: finish: modules-final/config-final-message: SUCCESS: config-final-message ran successfully
May 01 17:07:10 cloud-init[2416]: main.py[DEBUG]: Ran 8 modules with 0 failures
May 01 17:07:10 cloud-init[2416]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp5aiO7B) - w: [644] 579 bytes/chars
May 01 17:07:10 cloud-init[2416]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmpPgbi4R) - w: [644] 66 bytes/chars
May 01 17:07:10 cloud-init[2416]: util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
May 01 17:07:10 cloud-init[2416]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
May 01 17:07:10 cloud-init[2416]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
May 01 17:07:10 cloud-init[2416]: util.py[DEBUG]: cloud-init mode 'modules' took 0.079 seconds (0.08)
May 01 17:07:10 cloud-init[2416]: handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
May 02 04:15:28 cloud-init[1877]: util.py[DEBUG]: Cloud-init v. 19.3-43.amzn2 running 'init-local' at Sun, 02 May 2021 04:15:28 +0000. Up 24.57 seconds.
May 02 04:15:28 cloud-init[1877]: main.py[DEBUG]: No kernel command line url found.
May 02 04:15:28 cloud-init[1877]: main.py[DEBUG]: Closing stdin.
May 02 04:15:28 cloud-init[1877]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
May 02 04:15:28 cloud-init[1877]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/data/no-net
May 02 04:15:29 cloud-init[1877]: handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Read 6684 bytes from /var/lib/cloud/instance/obj.pkl
May 02 04:15:29 cloud-init[1877]: stages.py[DEBUG]: cache invalid in datasource: DataSourceNone
May 02 04:15:29 cloud-init[1877]: handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: cache invalid in datasource: DataSourceNone
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
May 02 04:15:29 cloud-init[1877]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
May 02 04:15:29 cloud-init[1877]: __init__.py[DEBUG]: Looking for data source in: ['NoCloud', 'AltCloud', 'ConfigDrive', 'OVF', 'None'], via packages ['', u'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
May 02 04:15:29 cloud-init[1877]: __init__.py[DEBUG]: Searching for local data source in: [u'DataSourceNoCloud', u'DataSourceConfigDrive', u'DataSourceOVF']
May 02 04:15:29 cloud-init[1877]: handlers.py[DEBUG]: start: init-local/search-NoCloud: searching for local data from DataSourceNoCloud
May 02 04:15:29 cloud-init[1877]: __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceNoCloud.DataSourceNoCloud'>
May 02 04:15:29 cloud-init[1877]: __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Read 1292 bytes from /proc/self/status
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/dmi/id/product_serial (quiet=False)
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Read 2 bytes from /sys/class/dmi/id/product_serial
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: dmi data /sys/class/dmi/id/product_serial returned 0
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/user-data (quiet=False)
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/meta-data (quiet=False)
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/vendor-data (quiet=False)
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/network-config (quiet=False)
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/user-data (quiet=False)
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/meta-data (quiet=False)
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/vendor-data (quiet=False)
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/network-config (quiet=False)
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Read 212 bytes from /etc/os-release
May 02 04:15:29 cloud-init[1877]: util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr0'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr1'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['blkid', '-tTYPE=vfat', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['blkid', '-tLABEL=CIDATA', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['blkid', '-tLABEL=cidata', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: __init__.py[DEBUG]: Datasource DataSourceNoCloud [seed=None][dsmode=net] not updated for events: New instance first boot
May 02 04:15:30 cloud-init[1877]: handlers.py[DEBUG]: finish: init-local/search-NoCloud: SUCCESS: no local data found from DataSourceNoCloud
May 02 04:15:30 cloud-init[1877]: handlers.py[DEBUG]: start: init-local/search-ConfigDrive: searching for local data from DataSourceConfigDrive
May 02 04:15:30 cloud-init[1877]: __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceConfigDrive.DataSourceConfigDrive'>
May 02 04:15:30 cloud-init[1877]: __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr0'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr1'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/cd0'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/cd1'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['blkid', '-tTYPE=vfat', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['blkid', '-tLABEL=config-2', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['blkid', '-tLABEL=CONFIG-2', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: DataSourceConfigDrive.py[DEBUG]: devices=[u'/dev/sr0'] dslist=['NoCloud', 'AltCloud', 'ConfigDrive', 'OVF', 'None']
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 212 bytes from /etc/os-release
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /proc/mounts (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 1920 bytes from /proc/mounts
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Fetched {'devpts': {'mountpoint': '/dev/pts', 'opts': 'rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000', 'fstype': 'devpts'}, 'debugfs': {'mountpoint': '/sys/kernel/debug', 'opts': 'rw,relatime', 'fstype': 'debugfs'}, 'securityfs': {'mountpoint': '/sys/kernel/security', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'securityfs'}, 'sysfs': {'mountpoint': '/sys', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'sysfs'}, 'mqueue': {'mountpoint': '/dev/mqueue', 'opts': 'rw,relatime', 'fstype': 'mqueue'}, 'pstore': {'mountpoint': '/sys/fs/pstore', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'pstore'}, '/dev/sda1': {'mountpoint': '/', 'opts': 'rw,noatime,attr2,inode64,noquota', 'fstype': 'xfs'}, 'hugetlbfs': {'mountpoint': '/dev/hugepages', 'opts': 'rw,relatime,pagesize=2M', 'fstype': 'hugetlbfs'}, 'cgroup': {'mountpoint': '/sys/fs/cgroup/blkio', 'opts': 'rw,nosuid,nodev,noexec,relatime,blkio', 'fstype': 'cgroup'}, 'sunrpc': {'mountpoint': '/var/lib/nfs/rpc_pipefs', 'opts': 'rw,relatime', 'fstype': 'rpc_pipefs'}, 'tmpfs': {'mountpoint': '/sys/fs/cgroup', 'opts': 'ro,nosuid,nodev,noexec,mode=755', 'fstype': 'tmpfs'}, 'proc': {'mountpoint': '/proc', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'proc'}, 'devtmpfs': {'mountpoint': '/dev', 'opts': 'rw,nosuid,size=486080k,nr_inodes=121520,mode=755', 'fstype': 'devtmpfs'}, 'systemd-1': {'mountpoint': '/proc/sys/fs/binfmt_misc', 'opts': 'rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=14161', 'fstype': 'autofs'}} mounts from proc
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['mount', '-o', 'ro', '-t', 'auto', u'/dev/sr0', '/run/cloud-init/tmp/tmpYNOaG4'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: openstack.py[DEBUG]: Unable to read openstack versions from /run/cloud-init/tmp/tmpYNOaG4/ due to: [Errno 2] No such file or directory: '/run/cloud-init/tmp/tmpYNOaG4/openstack'
May 02 04:15:30 cloud-init[1877]: openstack.py[DEBUG]: Selected version 'latest' from []
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpYNOaG4/openstack/latest/vendor_data.json (quiet=False)
May 02 04:15:30 cloud-init[1877]: openstack.py[DEBUG]: Failed reading optional path /run/cloud-init/tmp/tmpYNOaG4/openstack/latest/vendor_data.json due to: [Errno 2] No such file or directory: '/run/cloud-init/tmp/tmpYNOaG4/openstack/latest/vendor_data.json'
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpYNOaG4/openstack/latest/user_data (quiet=False)
May 02 04:15:30 cloud-init[1877]: openstack.py[DEBUG]: Failed reading optional path /run/cloud-init/tmp/tmpYNOaG4/openstack/latest/user_data due to: [Errno 2] No such file or directory: '/run/cloud-init/tmp/tmpYNOaG4/openstack/latest/user_data'
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpYNOaG4/openstack/latest/network_data.json (quiet=False)
May 02 04:15:30 cloud-init[1877]: openstack.py[DEBUG]: Failed reading optional path /run/cloud-init/tmp/tmpYNOaG4/openstack/latest/network_data.json due to: [Errno 2] No such file or directory: '/run/cloud-init/tmp/tmpYNOaG4/openstack/latest/network_data.json'
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /run/cloud-init/tmp/tmpYNOaG4/openstack/latest/meta_data.json (quiet=False)
May 02 04:15:30 cloud-init[1877]: openstack.py[DEBUG]: Failed reading mandatory path /run/cloud-init/tmp/tmpYNOaG4/openstack/latest/meta_data.json due to: [Errno 2] No such file or directory: '/run/cloud-init/tmp/tmpYNOaG4/openstack/latest/meta_data.json'
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['umount', '/run/cloud-init/tmp/tmpYNOaG4'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: __init__.py[DEBUG]: Datasource DataSourceConfigDrive [net,ver=None][source=None] not updated for events: New instance first boot
May 02 04:15:30 cloud-init[1877]: handlers.py[DEBUG]: finish: init-local/search-ConfigDrive: SUCCESS: no local data found from DataSourceConfigDrive
May 02 04:15:30 cloud-init[1877]: handlers.py[DEBUG]: start: init-local/search-OVF: searching for local data from DataSourceOVF
May 02 04:15:30 cloud-init[1877]: __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceOVF.DataSourceOVF'>
May 02 04:15:30 cloud-init[1877]: __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 1292 bytes from /proc/self/status
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/dmi/id/product_name (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 11 bytes from /sys/class/dmi/id/product_name
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: dmi data /sys/class/dmi/id/product_name returned VirtualBox
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /proc/mounts (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 1920 bytes from /proc/mounts
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Fetched {'devpts': {'mountpoint': '/dev/pts', 'opts': 'rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000', 'fstype': 'devpts'}, 'debugfs': {'mountpoint': '/sys/kernel/debug', 'opts': 'rw,relatime', 'fstype': 'debugfs'}, 'securityfs': {'mountpoint': '/sys/kernel/security', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'securityfs'}, 'sysfs': {'mountpoint': '/sys', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'sysfs'}, 'mqueue': {'mountpoint': '/dev/mqueue', 'opts': 'rw,relatime', 'fstype': 'mqueue'}, 'pstore': {'mountpoint': '/sys/fs/pstore', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'pstore'}, '/dev/sda1': {'mountpoint': '/', 'opts': 'rw,noatime,attr2,inode64,noquota', 'fstype': 'xfs'}, 'hugetlbfs': {'mountpoint': '/dev/hugepages', 'opts': 'rw,relatime,pagesize=2M', 'fstype': 'hugetlbfs'}, 'cgroup': {'mountpoint': '/sys/fs/cgroup/blkio', 'opts': 'rw,nosuid,nodev,noexec,relatime,blkio', 'fstype': 'cgroup'}, 'sunrpc': {'mountpoint': '/var/lib/nfs/rpc_pipefs', 'opts': 'rw,relatime', 'fstype': 'rpc_pipefs'}, 'tmpfs': {'mountpoint': '/sys/fs/cgroup', 'opts': 'ro,nosuid,nodev,noexec,mode=755', 'fstype': 'tmpfs'}, 'proc': {'mountpoint': '/proc', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'proc'}, 'devtmpfs': {'mountpoint': '/dev', 'opts': 'rw,nosuid,size=486080k,nr_inodes=121520,mode=755', 'fstype': 'devtmpfs'}, 'systemd-1': {'mountpoint': '/proc/sys/fs/binfmt_misc', 'opts': 'rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=14161', 'fstype': 'autofs'}} mounts from proc
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /proc/mounts (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 1920 bytes from /proc/mounts
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Fetched {'devpts': {'mountpoint': '/dev/pts', 'opts': 'rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000', 'fstype': 'devpts'}, 'debugfs': {'mountpoint': '/sys/kernel/debug', 'opts': 'rw,relatime', 'fstype': 'debugfs'}, 'securityfs': {'mountpoint': '/sys/kernel/security', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'securityfs'}, 'sysfs': {'mountpoint': '/sys', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'sysfs'}, 'mqueue': {'mountpoint': '/dev/mqueue', 'opts': 'rw,relatime', 'fstype': 'mqueue'}, 'pstore': {'mountpoint': '/sys/fs/pstore', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'pstore'}, '/dev/sda1': {'mountpoint': '/', 'opts': 'rw,noatime,attr2,inode64,noquota', 'fstype': 'xfs'}, 'hugetlbfs': {'mountpoint': '/dev/hugepages', 'opts': 'rw,relatime,pagesize=2M', 'fstype': 'hugetlbfs'}, 'cgroup': {'mountpoint': '/sys/fs/cgroup/blkio', 'opts': 'rw,nosuid,nodev,noexec,relatime,blkio', 'fstype': 'cgroup'}, 'sunrpc': {'mountpoint': '/var/lib/nfs/rpc_pipefs', 'opts': 'rw,relatime', 'fstype': 'rpc_pipefs'}, 'tmpfs': {'mountpoint': '/sys/fs/cgroup', 'opts': 'ro,nosuid,nodev,noexec,mode=755', 'fstype': 'tmpfs'}, 'proc': {'mountpoint': '/proc', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'proc'}, 'devtmpfs': {'mountpoint': '/dev', 'opts': 'rw,nosuid,size=486080k,nr_inodes=121520,mode=755', 'fstype': 'devtmpfs'}, 'systemd-1': {'mountpoint': '/proc/sys/fs/binfmt_misc', 'opts': 'rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=14161', 'fstype': 'autofs'}} mounts from proc
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['mount', '-o', 'ro', '-t', 'iso9660', u'/dev/sr0', '/run/cloud-init/tmp/tmpeISOPO'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['umount', '/run/cloud-init/tmp/tmpeISOPO'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: __init__.py[DEBUG]: Datasource DataSourceOVF [seed=None] not updated for events: New instance first boot
May 02 04:15:30 cloud-init[1877]: handlers.py[DEBUG]: finish: init-local/search-OVF: SUCCESS: no local data found from DataSourceOVF
May 02 04:15:30 cloud-init[1877]: main.py[DEBUG]: No local datasource found
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
May 02 04:15:30 cloud-init[1877]: __init__.py[DEBUG]: Stable ifnames disabled by net.ifnames=0 in /proc/cmdline
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/eth0/carrier (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/eth0/dormant (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/eth0/operstate (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 5 bytes from /sys/class/net/eth0/operstate
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/eth0/device/device (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 7 bytes from /sys/class/net/eth0/device/device
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/eth0/addr_assign_type (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/addr_assign_type
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/eth0/uevent (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 25 bytes from /sys/class/net/eth0/uevent
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/eth0/device/device (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 7 bytes from /sys/class/net/eth0/device/device
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/eth0/type (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/type
May 02 04:15:30 cloud-init[1877]: __init__.py[DEBUG]: net: all expected physical devices present
May 02 04:15:30 cloud-init[1877]: stages.py[DEBUG]: applying net config names for {'ethernets': {'eth0': {'set-name': 'eth0', 'match': {'macaddress': '08:00:27:bb:8f:83'}, 'dhcp4': True}}, 'version': 2}
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/eth0/device/device (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 7 bytes from /sys/class/net/eth0/device/device
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/eth0/addr_assign_type (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/addr_assign_type
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/eth0/uevent (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 25 bytes from /sys/class/net/eth0/uevent
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/eth0/device/device (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 7 bytes from /sys/class/net/eth0/device/device
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /sys/class/net/eth0/operstate (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 5 bytes from /sys/class/net/eth0/operstate
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:30 cloud-init[1877]: __init__.py[DEBUG]: no work necessary for renaming of [['08:00:27:bb:8f:83', 'eth0', 'e1000', '0x100e']]
May 02 04:15:30 cloud-init[1877]: stages.py[INFO]: Applying network configuration from fallback bringup=False: {'ethernets': {'eth0': {'set-name': 'eth0', 'match': {'macaddress': '08:00:27:bb:8f:83'}, 'dhcp4': True}}, 'version': 2}
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 212 bytes from /etc/os-release
May 02 04:15:30 cloud-init[1877]: stages.py[ERROR]: Unable to render networking. Network config is likely broken: No available network renderers found. Searched through list: ['eni', 'sysconfig', 'netplan']
May 02 04:15:30 cloud-init[1877]: main.py[DEBUG]: [local] Exiting without datasource
May 02 04:15:30 cloud-init[1877]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp5tMGnV) - w: [644] 489 bytes/chars
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
May 02 04:15:30 cloud-init[1877]: util.py[DEBUG]: cloud-init mode 'init' took 2.274 seconds (2.28)
May 02 04:15:30 cloud-init[1877]: handlers.py[DEBUG]: finish: init-local: SUCCESS: searching for local datasources
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Cloud-init v. 19.3-43.amzn2 running 'init' at Sun, 02 May 2021 04:15:44 +0000. Up 40.01 seconds.
May 02 04:15:44 cloud-init[2238]: main.py[DEBUG]: No kernel command line url found.
May 02 04:15:44 cloud-init[2238]: main.py[DEBUG]: Closing stdin.
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['ip', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: main.py[DEBUG]: Checking to see if files that we need already exist from a previous run that would allow us to stop early.
May 02 04:15:44 cloud-init[2238]: main.py[DEBUG]: Execution continuing, no previous run detected that would allow us to stop early.
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
May 02 04:15:44 cloud-init[2238]: stages.py[DEBUG]: no cache found
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
May 02 04:15:44 cloud-init[2238]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Looking for data source in: ['NoCloud', 'AltCloud', 'ConfigDrive', 'OVF', 'None'], via packages ['', u'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Searching for network data source in: [u'DataSourceNoCloudNet', u'DataSourceAltCloud', u'DataSourceOVFNet', u'DataSourceNone']
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/search-NoCloudNet: searching for network data from DataSourceNoCloudNet
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceNoCloud.DataSourceNoCloudNet'>
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 1291 bytes from /proc/self/status
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/dmi/id/product_serial (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 2 bytes from /sys/class/dmi/id/product_serial
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: dmi data /sys/class/dmi/id/product_serial returned 0
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/user-data (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/meta-data (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/vendor-data (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud/network-config (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/user-data (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/meta-data (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/vendor-data (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /var/lib/cloud/seed/nocloud-net/network-config (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 212 bytes from /etc/os-release
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr0'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['blkid', '-odevice', '/dev/sr1'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['blkid', '-tTYPE=vfat', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['blkid', '-tLABEL=CIDATA', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['blkid', '-tLABEL=cidata', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Datasource DataSourceNoCloudNet [seed=None][dsmode=net] not updated for events: New instance first boot
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/search-NoCloudNet: SUCCESS: no network data found from DataSourceNoCloudNet
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/search-AltCloud: searching for network data from DataSourceAltCloud
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceAltCloud.DataSourceAltCloud'>
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
May 02 04:15:44 cloud-init[2238]: DataSourceAltCloud.py[DEBUG]: Invoked get_data()
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 1291 bytes from /proc/self/status
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/dmi/id/product_name (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 11 bytes from /sys/class/dmi/id/product_name
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: dmi data /sys/class/dmi/id/product_name returned VirtualBox
May 02 04:15:44 cloud-init[2238]: DataSourceAltCloud.py[DEBUG]: cloud_type: UNKNOWN
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Datasource DataSourceAltCloud [seed=None] not updated for events: New instance first boot
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/search-AltCloud: SUCCESS: no network data found from DataSourceAltCloud
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/search-OVFNet: searching for network data from DataSourceOVFNet
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceOVF.DataSourceOVFNet'>
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 1291 bytes from /proc/self/status
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_name
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/dmi/id/product_name (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 11 bytes from /sys/class/dmi/id/product_name
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: dmi data /sys/class/dmi/id/product_name returned VirtualBox
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /proc/mounts (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 1920 bytes from /proc/mounts
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Fetched {'devpts': {'mountpoint': '/dev/pts', 'opts': 'rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000', 'fstype': 'devpts'}, 'debugfs': {'mountpoint': '/sys/kernel/debug', 'opts': 'rw,relatime', 'fstype': 'debugfs'}, 'securityfs': {'mountpoint': '/sys/kernel/security', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'securityfs'}, 'sysfs': {'mountpoint': '/sys', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'sysfs'}, 'mqueue': {'mountpoint': '/dev/mqueue', 'opts': 'rw,relatime', 'fstype': 'mqueue'}, 'pstore': {'mountpoint': '/sys/fs/pstore', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'pstore'}, '/dev/sda1': {'mountpoint': '/', 'opts': 'rw,noatime,attr2,inode64,noquota', 'fstype': 'xfs'}, 'hugetlbfs': {'mountpoint': '/dev/hugepages', 'opts': 'rw,relatime,pagesize=2M', 'fstype': 'hugetlbfs'}, 'cgroup': {'mountpoint': '/sys/fs/cgroup/blkio', 'opts': 'rw,nosuid,nodev,noexec,relatime,blkio', 'fstype': 'cgroup'}, 'sunrpc': {'mountpoint': '/var/lib/nfs/rpc_pipefs', 'opts': 'rw,relatime', 'fstype': 'rpc_pipefs'}, 'tmpfs': {'mountpoint': '/sys/fs/cgroup', 'opts': 'ro,nosuid,nodev,noexec,mode=755', 'fstype': 'tmpfs'}, 'proc': {'mountpoint': '/proc', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'proc'}, 'devtmpfs': {'mountpoint': '/dev', 'opts': 'rw,nosuid,size=486080k,nr_inodes=121520,mode=755', 'fstype': 'devtmpfs'}, 'systemd-1': {'mountpoint': '/proc/sys/fs/binfmt_misc', 'opts': 'rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=14161', 'fstype': 'autofs'}} mounts from proc
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['blkid', '-tTYPE=iso9660', '-odevice'] with allowed return codes [0, 2] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /proc/mounts (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 1920 bytes from /proc/mounts
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Fetched {'devpts': {'mountpoint': '/dev/pts', 'opts': 'rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000', 'fstype': 'devpts'}, 'debugfs': {'mountpoint': '/sys/kernel/debug', 'opts': 'rw,relatime', 'fstype': 'debugfs'}, 'securityfs': {'mountpoint': '/sys/kernel/security', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'securityfs'}, 'sysfs': {'mountpoint': '/sys', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'sysfs'}, 'mqueue': {'mountpoint': '/dev/mqueue', 'opts': 'rw,relatime', 'fstype': 'mqueue'}, 'pstore': {'mountpoint': '/sys/fs/pstore', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'pstore'}, '/dev/sda1': {'mountpoint': '/', 'opts': 'rw,noatime,attr2,inode64,noquota', 'fstype': 'xfs'}, 'hugetlbfs': {'mountpoint': '/dev/hugepages', 'opts': 'rw,relatime,pagesize=2M', 'fstype': 'hugetlbfs'}, 'cgroup': {'mountpoint': '/sys/fs/cgroup/blkio', 'opts': 'rw,nosuid,nodev,noexec,relatime,blkio', 'fstype': 'cgroup'}, 'sunrpc': {'mountpoint': '/var/lib/nfs/rpc_pipefs', 'opts': 'rw,relatime', 'fstype': 'rpc_pipefs'}, 'tmpfs': {'mountpoint': '/sys/fs/cgroup', 'opts': 'ro,nosuid,nodev,noexec,mode=755', 'fstype': 'tmpfs'}, 'proc': {'mountpoint': '/proc', 'opts': 'rw,nosuid,nodev,noexec,relatime', 'fstype': 'proc'}, 'devtmpfs': {'mountpoint': '/dev', 'opts': 'rw,nosuid,size=486080k,nr_inodes=121520,mode=755', 'fstype': 'devtmpfs'}, 'systemd-1': {'mountpoint': '/proc/sys/fs/binfmt_misc', 'opts': 'rw,relatime,fd=30,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=14161', 'fstype': 'autofs'}} mounts from proc
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['mount', '-o', 'ro', '-t', 'iso9660', u'/dev/sr0', '/run/cloud-init/tmp/tmplMmQQy'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['umount', '/run/cloud-init/tmp/tmplMmQQy'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Datasource DataSourceOVFNet [seed=None] not updated for events: New instance first boot
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/search-OVFNet: SUCCESS: no network data found from DataSourceOVFNet
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/search-None: searching for network data from DataSourceNone
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceNone.DataSourceNone'>
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Update datasource metadata and network config due to events: New instance first boot
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /etc/hosts (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 177 bytes from /etc/hosts
May 02 04:15:44 cloud-init[2238]: atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpbPZBo1) - w: [644] 631 bytes/chars
May 02 04:15:44 cloud-init[2238]: atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmpE3obZg) - w: [600] 631 bytes/chars
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/search-None: SUCCESS: found network data from DataSourceNone
May 02 04:15:44 cloud-init[2238]: stages.py[INFO]: Loaded datasource DataSourceNone - DataSourceNone
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 1258 bytes from /etc/cloud/cloud.cfg
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Attempting to load yaml from string of length 1258 with allowed root types (<type 'dict'>,)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 590 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Attempting to load yaml from string of length 590 with allowed root types (<type 'dict'>,)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 2120 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Attempting to load yaml from string of length 2120 with allowed root types (<type 'dict'>,)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: loaded blob returned None, returning default.
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/iid-datasource-none'
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /var/lib/cloud/instances/iid-datasource-none/datasource (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 31 bytes from /var/lib/cloud/instances/iid-datasource-none/datasource
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/datasource - wb: [644] 31 bytes
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 31 bytes
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 20 bytes from /var/lib/cloud/data/instance-id
May 02 04:15:44 cloud-init[2238]: stages.py[DEBUG]: previous iid found to be iid-datasource-none
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 20 bytes
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 5056 bytes
May 02 04:15:44 cloud-init[2238]: main.py[DEBUG]: [net] init will now be targeting instance id: iid-datasource-none. new=False
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 1258 bytes from /etc/cloud/cloud.cfg
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Attempting to load yaml from string of length 1258 with allowed root types (<type 'dict'>,)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 590 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Attempting to load yaml from string of length 590 with allowed root types (<type 'dict'>,)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 2120 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Attempting to load yaml from string of length 2120 with allowed root types (<type 'dict'>,)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: loaded blob returned None, returning default.
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: loaded blob returned None, returning default.
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
May 02 04:15:44 cloud-init[2238]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Stable ifnames disabled by net.ifnames=0 in /proc/cmdline
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/net/eth0/carrier (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/carrier
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Datasource DataSourceNone not updated for events: System boot
May 02 04:15:44 cloud-init[2238]: stages.py[DEBUG]: No network config applied. Neither a new instance nor datasource network update on 'System boot' event
May 02 04:15:44 cloud-init[2238]: stages.py[DEBUG]: applying net config names for {'ethernets': {'eth0': {'set-name': 'eth0', 'match': {'macaddress': '08:00:27:bb:8f:83'}, 'dhcp4': True}}, 'version': 2}
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/net/eth0/device/device (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 7 bytes from /sys/class/net/eth0/device/device
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/net/eth0/addr_assign_type (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 2 bytes from /sys/class/net/eth0/addr_assign_type
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/net/eth0/uevent (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 25 bytes from /sys/class/net/eth0/uevent
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/net/eth0/address (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 18 bytes from /sys/class/net/eth0/address
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/net/eth0/device/device (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 7 bytes from /sys/class/net/eth0/device/device
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/net/lo/operstate (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 8 bytes from /sys/class/net/lo/operstate
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/net/eth0/operstate (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 3 bytes from /sys/class/net/eth0/operstate
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['ip', '-6', 'addr', 'show', 'permanent', 'scope', 'global'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['ip', '-4', 'addr', 'show'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: no work necessary for renaming of [['08:00:27:bb:8f:83', 'eth0', 'e1000', '0x100e']]
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/user-data.txt - wb: [600] 0 bytes
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/user-data.txt.i - wb: [600] 345 bytes
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/vendor-data.txt - wb: [600] 0 bytes
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/vendor-data.txt.i - wb: [600] 345 bytes
May 02 04:15:44 cloud-init[2238]: helpers.py[DEBUG]: consume_data already ran (freq=once-per-instance)
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
May 02 04:15:44 cloud-init[2238]: stages.py[DEBUG]: Added default handler for set(['text/cloud-config-jsonp', 'text/cloud-config']) from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
May 02 04:15:44 cloud-init[2238]: stages.py[DEBUG]: Added default handler for set(['text/x-shellscript']) from ShellScriptPartHandler: [['text/x-shellscript']]
May 02 04:15:44 cloud-init[2238]: stages.py[DEBUG]: Added default handler for set(['text/cloud-boothook']) from BootHookPartHandler: [['text/cloud-boothook']]
May 02 04:15:44 cloud-init[2238]: stages.py[DEBUG]: Added default handler for set(['text/upstart-job']) from UpstartJobPartHandler: [['text/upstart-job']]
May 02 04:15:44 cloud-init[2238]: stages.py[DEBUG]: Added default handler for set(['text/jinja2']) from JinjaTemplatePartHandler: [['text/jinja2']]
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency always
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency always
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency always
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency always
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: {'Content-Type': 'text/x-not-multipart', 'Content-Disposition': 'attachment; filename="part-001"', 'MIME-Version': '1.0'}
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Empty payload of type text/x-not-multipart
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency always
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/cloud-config.txt - wb: [600] 0 bytes
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency always
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency always
May 02 04:15:44 cloud-init[2238]: __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency always
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
May 02 04:15:44 cloud-init[2238]: stages.py[DEBUG]: no vendordata from datasource
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 1258 bytes from /etc/cloud/cloud.cfg
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Attempting to load yaml from string of length 1258 with allowed root types (<type 'dict'>,)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 590 bytes from /etc/cloud/cloud.cfg.d/10_aws_yumvars.cfg
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Attempting to load yaml from string of length 590 with allowed root types (<type 'dict'>,)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 2120 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Attempting to load yaml from string of length 2120 with allowed root types (<type 'dict'>,)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: loaded blob returned None, returning default.
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: loaded blob returned None, returning default.
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 0 bytes from /var/lib/cloud/instance/cloud-config.txt
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<type 'dict'>,)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: loaded blob returned None, returning default.
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 6684 bytes
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
May 02 04:15:44 cloud-init[2238]: main.py[DEBUG]: no di_report found in config.
May 02 04:15:44 cloud-init[2238]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
May 02 04:15:44 cloud-init[2238]: stages.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_migrator.pyc'>) with frequency always
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
May 02 04:15:44 cloud-init[2238]: helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7fdccd02d390>)
May 02 04:15:44 cloud-init[2238]: cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
May 02 04:15:44 cloud-init[2238]: stages.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_bootcmd.pyc'>) with frequency always
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
May 02 04:15:44 cloud-init[2238]: helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7fdccd02d3d0>)
May 02 04:15:44 cloud-init[2238]: cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
May 02 04:15:44 cloud-init[2238]: stages.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_write_files.pyc'>) with frequency once-per-instance
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
May 02 04:15:44 cloud-init[2238]: helpers.py[DEBUG]: config-write-files already ran (freq=once-per-instance)
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files previously ran
May 02 04:15:44 cloud-init[2238]: stages.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_growpart.pyc'>) with frequency always
May 02 04:15:44 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
May 02 04:15:44 cloud-init[2238]: helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7fdccd02d6d0>)
May 02 04:15:44 cloud-init[2238]: cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'ignore_growroot_disabled': False, 'mode': 'auto', 'devices': ['/']}
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /proc/2238/mountinfo (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 2529 bytes from /proc/2238/mountinfo
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 1292 bytes from /proc/self/status
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /etc/os-release (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 212 bytes from /etc/os-release
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/class/block/sda1/partition (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 2 bytes from /sys/class/block/sda1/partition
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Reading from /sys/devices/pci0000:00/0000:00:01.1/ata1/host0/target0:0:0/0:0:0:0/block/sda/dev (quiet=False)
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Read 4 bytes from /sys/devices/pci0000:00/0000:00:01.1/ata1/host0/target0:0:0/0:0:0:0/block/sda/dev
May 02 04:15:44 cloud-init[2238]: util.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/sda', '1'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: resize_devices took 0.152 seconds
May 02 04:15:45 cloud-init[2238]: cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/sda, 1)
May 02 04:15:45 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
May 02 04:15:45 cloud-init[2238]: stages.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_resizefs.pyc'>) with frequency always
May 02 04:15:45 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
May 02 04:15:45 cloud-init[2238]: helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7fdccd0d2dd0>)
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: Reading from /proc/2238/mountinfo (quiet=False)
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: Read 2529 bytes from /proc/2238/mountinfo
May 02 04:15:45 cloud-init[2238]: cc_resizefs.py[DEBUG]: resize_info: dev=/dev/sda1 mnt_point=/ path=/
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: Running command ['systemd-detect-virt', '--quiet', '--container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: Running command ['running-in-container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: Running command ['lxc-is-container'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: Reading from /proc/1/environ (quiet=False)
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: Read 0 bytes from /proc/1/environ
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: Reading from /proc/self/status (quiet=False)
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: Read 1292 bytes from /proc/self/status
May 02 04:15:45 cloud-init[2238]: cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: Forked child 2380 who will run callback log_time
May 02 04:15:45 cloud-init[2238]: cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
May 02 04:15:45 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
May 02 04:15:45 cloud-init[2238]: stages.py[DEBUG]: Running module set-hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_set_hostname.pyc'>) with frequency once-per-instance
May 02 04:15:45 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/config-set-hostname: running config-set-hostname with frequency once-per-instance
May 02 04:15:45 cloud-init[2238]: helpers.py[DEBUG]: config-set-hostname already ran (freq=once-per-instance)
May 02 04:15:45 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/config-set-hostname: SUCCESS: config-set-hostname previously ran
May 02 04:15:45 cloud-init[2238]: stages.py[DEBUG]: Running module update-hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_update_hostname.pyc'>) with frequency always
May 02 04:15:45 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/config-update-hostname: running config-update-hostname with frequency always
May 02 04:15:45 cloud-init[2238]: helpers.py[DEBUG]: Running config-update-hostname using lock (<cloudinit.helpers.DummyLock object at 0x7fdcccc39350>)
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: Reading from /etc/hosts (quiet=False)
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: Read 177 bytes from /etc/hosts
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: Reading from /etc/hosts (quiet=False)
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: Read 177 bytes from /etc/hosts
May 02 04:15:45 cloud-init[2238]: cc_update_hostname.py[DEBUG]: Updating hostname to master1.local (master1)
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: Reading from /var/lib/cloud/data/previous-hostname (quiet=False)
May 02 04:15:45 cloud-init[2380]: util.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: Read 9 bytes from /var/lib/cloud/data/previous-hostname
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
May 02 04:15:45 cloud-init[2238]: __init__.py[INFO]: /var/lib/cloud/data/previous-hostname differs from /etc/hostname, assuming user maintained hostname.
May 02 04:15:45 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/config-update-hostname: SUCCESS: config-update-hostname ran successfully
May 02 04:15:45 cloud-init[2238]: stages.py[DEBUG]: Running module update-etc-hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_update_etc_hosts.pyc'>) with frequency always
May 02 04:15:45 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/config-update-etc-hosts: running config-update-etc-hosts with frequency always
May 02 04:15:45 cloud-init[2238]: helpers.py[DEBUG]: Running config-update-etc-hosts using lock (<cloudinit.helpers.DummyLock object at 0x7fdcccc39290>)
May 02 04:15:45 cloud-init[2238]: cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update-etc-hosts
May 02 04:15:45 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/config-update-etc-hosts: SUCCESS: config-update-etc-hosts ran successfully
May 02 04:15:45 cloud-init[2238]: stages.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_rsyslog.pyc'>) with frequency once-per-instance
May 02 04:15:45 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
May 02 04:15:45 cloud-init[2238]: helpers.py[DEBUG]: config-rsyslog already ran (freq=once-per-instance)
May 02 04:15:45 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog previously ran
May 02 04:15:45 cloud-init[2238]: stages.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_users_groups.pyc'>) with frequency once-per-instance
May 02 04:15:45 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
May 02 04:15:45 cloud-init[2238]: helpers.py[DEBUG]: config-users-groups already ran (freq=once-per-instance)
May 02 04:15:45 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups previously ran
May 02 04:15:45 cloud-init[2238]: stages.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_ssh.pyc'>) with frequency once-per-instance
May 02 04:15:45 cloud-init[2238]: handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
May 02 04:15:45 cloud-init[2238]: helpers.py[DEBUG]: config-ssh already ran (freq=once-per-instance)
May 02 04:15:45 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh previously ran
May 02 04:15:45 cloud-init[2238]: main.py[DEBUG]: Ran 11 modules with 0 failures
May 02 04:15:45 cloud-init[2238]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpzu0Oi7) - w: [644] 527 bytes/chars
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
May 02 04:15:45 cloud-init[2238]: util.py[DEBUG]: cloud-init mode 'init' took 1.124 seconds (1.12)
May 02 04:15:45 cloud-init[2238]: handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
May 02 04:15:45 cloud-init[2380]: util.py[DEBUG]: backgrounded Resizing took 0.034 seconds
May 02 04:15:45 cloud-init[2388]: util.py[DEBUG]: Cloud-init v. 19.3-43.amzn2 running 'modules:config' at Sun, 02 May 2021 04:15:45 +0000. Up 41.51 seconds.
May 02 04:15:45 cloud-init[2388]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
May 02 04:15:45 cloud-init[2388]: stages.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_mounts.pyc'>) with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: start: modules-config/config-mounts: running config-mounts with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: helpers.py[DEBUG]: config-mounts already ran (freq=once-per-instance)
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: finish: modules-config/config-mounts: SUCCESS: config-mounts previously ran
May 02 04:15:45 cloud-init[2388]: stages.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_locale.pyc'>) with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: helpers.py[DEBUG]: config-locale already ran (freq=once-per-instance)
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale previously ran
May 02 04:15:45 cloud-init[2388]: stages.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_set_passwords.pyc'>) with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: helpers.py[DEBUG]: config-set-passwords already ran (freq=once-per-instance)
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords previously ran
May 02 04:15:45 cloud-init[2388]: stages.py[DEBUG]: Running module yum-configure (<module 'cloudinit.config.cc_yum_configure' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_yum_configure.pyc'>) with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: start: modules-config/config-yum-configure: running config-yum-configure with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: helpers.py[DEBUG]: config-yum-configure already ran (freq=once-per-instance)
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: finish: modules-config/config-yum-configure: SUCCESS: config-yum-configure previously ran
May 02 04:15:45 cloud-init[2388]: stages.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_yum_add_repo.pyc'>) with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: helpers.py[DEBUG]: config-yum-add-repo already ran (freq=once-per-instance)
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo previously ran
May 02 04:15:45 cloud-init[2388]: stages.py[DEBUG]: Running module package-update-upgrade-install (<module 'cloudinit.config.cc_package_update_upgrade_install' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_package_update_upgrade_install.pyc'>) with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: start: modules-config/config-package-update-upgrade-install: running config-package-update-upgrade-install with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: helpers.py[DEBUG]: config-package-update-upgrade-install already ran (freq=once-per-instance)
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: finish: modules-config/config-package-update-upgrade-install: SUCCESS: config-package-update-upgrade-install previously ran
May 02 04:15:45 cloud-init[2388]: stages.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_timezone.pyc'>) with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: helpers.py[DEBUG]: config-timezone already ran (freq=once-per-instance)
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone previously ran
May 02 04:15:45 cloud-init[2388]: stages.py[DEBUG]: Running module puppet (<module 'cloudinit.config.cc_puppet' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_puppet.pyc'>) with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: start: modules-config/config-puppet: running config-puppet with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: helpers.py[DEBUG]: config-puppet already ran (freq=once-per-instance)
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: finish: modules-config/config-puppet: SUCCESS: config-puppet previously ran
May 02 04:15:45 cloud-init[2388]: stages.py[DEBUG]: Running module chef (<module 'cloudinit.config.cc_chef' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_chef.pyc'>) with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: start: modules-config/config-chef: running config-chef with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: helpers.py[DEBUG]: config-chef already ran (freq=once-per-instance)
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: finish: modules-config/config-chef: SUCCESS: config-chef previously ran
May 02 04:15:45 cloud-init[2388]: stages.py[DEBUG]: Running module salt-minion (<module 'cloudinit.config.cc_salt_minion' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_salt_minion.pyc'>) with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: start: modules-config/config-salt-minion: running config-salt-minion with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: helpers.py[DEBUG]: config-salt-minion already ran (freq=once-per-instance)
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: finish: modules-config/config-salt-minion: SUCCESS: config-salt-minion previously ran
May 02 04:15:45 cloud-init[2388]: stages.py[DEBUG]: Running module mcollective (<module 'cloudinit.config.cc_mcollective' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_mcollective.pyc'>) with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: start: modules-config/config-mcollective: running config-mcollective with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: helpers.py[DEBUG]: config-mcollective already ran (freq=once-per-instance)
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: finish: modules-config/config-mcollective: SUCCESS: config-mcollective previously ran
May 02 04:15:45 cloud-init[2388]: stages.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_disable_ec2_metadata.pyc'>) with frequency always
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
May 02 04:15:45 cloud-init[2388]: helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7f7fc23f0410>)
May 02 04:15:45 cloud-init[2388]: cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
May 02 04:15:45 cloud-init[2388]: stages.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_runcmd.pyc'>) with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: handlers.py[FAILED]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
May 02 04:15:45 cloud-init[2388]: helpers.py[DEBUG]: config-runcmd already ran (freq=once-per-instance)
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd previously ran
May 02 04:15:45 cloud-init[2388]: main.py[DEBUG]: Ran 13 modules with 0 failures
May 02 04:15:45 cloud-init[2388]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpYX98yK) - w: [644] 553 bytes/chars
May 02 04:15:45 cloud-init[2388]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
May 02 04:15:45 cloud-init[2388]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
May 02 04:15:45 cloud-init[2388]: util.py[DEBUG]: cloud-init mode 'modules' took 0.215 seconds (0.21)
May 02 04:15:45 cloud-init[2388]: handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
May 02 04:15:46 cloud-init[2427]: util.py[DEBUG]: Cloud-init v. 19.3-43.amzn2 running 'modules:final' at Sun, 02 May 2021 04:15:46 +0000. Up 42.07 seconds.
May 02 04:15:46 cloud-init[2427]: stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
May 02 04:15:46 cloud-init[2427]: stages.py[DEBUG]: Running module scripts-per-once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_per_once.pyc'>) with frequency once
May 02 04:15:46 cloud-init[2427]: handlers.py[DEBUG]: start: modules-final/config-scripts-per-once: running config-scripts-per-once with frequency once
May 02 04:15:46 cloud-init[2427]: helpers.py[DEBUG]: config-scripts-per-once already ran (freq=once)
May 02 04:15:46 cloud-init[2427]: handlers.py[DEBUG]: finish: modules-final/config-scripts-per-once: SUCCESS: config-scripts-per-once previously ran
May 02 04:15:46 cloud-init[2427]: stages.py[DEBUG]: Running module scripts-per-boot (<module 'cloudinit.config.cc_scripts_per_boot' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_per_boot.pyc'>) with frequency always
May 02 04:15:46 cloud-init[2427]: handlers.py[DEBUG]: start: modules-final/config-scripts-per-boot: running config-scripts-per-boot with frequency always
May 02 04:15:46 cloud-init[2427]: helpers.py[DEBUG]: Running config-scripts-per-boot using lock (<cloudinit.helpers.DummyLock object at 0x7faafbd6c410>)
May 02 04:15:46 cloud-init[2427]: handlers.py[DEBUG]: finish: modules-final/config-scripts-per-boot: SUCCESS: config-scripts-per-boot ran successfully
May 02 04:15:46 cloud-init[2427]: stages.py[DEBUG]: Running module scripts-per-instance (<module 'cloudinit.config.cc_scripts_per_instance' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_per_instance.pyc'>) with frequency once-per-instance
May 02 04:15:46 cloud-init[2427]: handlers.py[DEBUG]: start: modules-final/config-scripts-per-instance: running config-scripts-per-instance with frequency once-per-instance
May 02 04:15:46 cloud-init[2427]: helpers.py[DEBUG]: config-scripts-per-instance already ran (freq=once-per-instance)
May 02 04:15:46 cloud-init[2427]: handlers.py[DEBUG]: finish: modules-final/config-scripts-per-instance: SUCCESS: config-scripts-per-instance previously ran
May 02 04:15:46 cloud-init[2427]: stages.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) with frequency once-per-instance
May 02 04:15:46 cloud-init[2427]: handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency once-per-instance
May 02 04:15:46 cloud-init[2427]: helpers.py[DEBUG]: config-scripts-user already ran (freq=once-per-instance)
May 02 04:15:46 cloud-init[2427]: handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user previously ran
May 02 04:15:46 cloud-init[2427]: stages.py[DEBUG]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_ssh_authkey_fingerprints.pyc'>) with frequency once-per-instance
May 02 04:15:46 cloud-init[2427]: handlers.py[DEBUG]: start: modules-final/config-ssh-authkey-fingerprints: running config-ssh-authkey-fingerprints with frequency once-per-instance
May 02 04:15:46 cloud-init[2427]: helpers.py[DEBUG]: config-ssh-authkey-fingerprints already ran (freq=once-per-instance)
May 02 04:15:46 cloud-init[2427]: handlers.py[DEBUG]: finish: modules-final/config-ssh-authkey-fingerprints: SUCCESS: config-ssh-authkey-fingerprints previously ran
May 02 04:15:46 cloud-init[2427]: stages.py[ERROR]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_keys_to_console.pyc'>) with frequency once-per-instance
May 02 04:15:46 cloud-init[2427]: handlers.py[DEBUG]: start: modules-final/config-keys-to-console: running config-keys-to-console with frequency once-per-instance
May 02 04:15:46 cloud-init[2427]: helpers.py[DEBUG]: config-keys-to-console already ran (freq=once-per-instance)
May 02 04:15:46 cloud-init[2427]: handlers.py[DEBUG]: finish: modules-final/config-keys-to-console: SUCCESS: config-keys-to-console previously ran
May 02 04:15:46 cloud-init[2427]: stages.py[DEBUG]: Running module phone-home (<module 'cloudinit.config.cc_phone_home' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_phone_home.pyc'>) with frequency once-per-instance
May 02 04:15:46 cloud-init[2427]: handlers.py[DEBUG]: start: modules-final/config-phone-home: running config-phone-home with frequency once-per-instance
May 02 04:15:46 cloud-init[2427]: helpers.py[DEBUG]: config-phone-home already ran (freq=once-per-instance)
May 02 04:15:46 cloud-init[2427]: handlers.py[DEBUG]: finish: modules-final/config-phone-home: SUCCESS: config-phone-home previously ran
May 02 04:15:46 cloud-init[2427]: stages.py[DEBUG]: Running module final-message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_final_message.pyc'>) with frequency always
May 02 04:15:46 cloud-init[2427]: handlers.py[DEBUG]: start: modules-final/config-final-message: running config-final-message with frequency always
May 02 04:15:46 cloud-init[2427]: helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x7faafbd6ca50>)
May 02 04:15:46 cloud-init[2427]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
May 02 04:15:46 cloud-init[2427]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
May 02 04:15:46 cloud-init[2427]: util.py[DEBUG]: Cloud-init v. 19.3-43.amzn2 finished at Sun, 02 May 2021 04:15:46 +0000. Datasource DataSourceNone.  Up 42.23 seconds
May 02 04:15:46 cloud-init[2427]: util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 59 bytes
May 02 04:15:46 cloud-init[2427]: cc_final_message.py[WARNING]: Used fallback datasource
May 02 04:15:46 cloud-init[2427]: handlers.py[DEBUG]: finish: modules-final/config-final-message: SUCCESS: config-final-message ran successfully
May 02 04:15:46 cloud-init[2427]: main.py[DEBUG]: Ran 8 modules with 0 failures
May 02 04:15:46 cloud-init[2427]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpW0DTpL) - w: [644] 578 bytes/chars
May 02 04:15:46 cloud-init[2427]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmp4bbJJ_) - w: [644] 66 bytes/chars
May 02 04:15:46 cloud-init[2427]: util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
May 02 04:15:46 cloud-init[2427]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
May 02 04:15:46 cloud-init[2427]: util.py[DEBUG]: Read 12 bytes from /proc/uptime
May 02 04:15:46 cloud-init[2427]: util.py[DEBUG]: cloud-init mode 'modules' took 0.168 seconds (0.17)
May 02 04:15:46 cloud-init[2427]: handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
